apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rogoyalguanew-e6ad"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rogoyalguanew-e6ad"
  template:
    metadata:
      labels:
        app: "rogoyalguanew-e6ad"
    spec:
      containers:
        - name: "rogoyalguanew-e6ad"
          image: "rogoyalacr.azurecr.io/rogoyalguanew"
          ports:
          - containerPort: 80