apiVersion : apps/v1
kind: Deployment
metadata:
  name: "rogoyalgua-493f"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "rogoyalgua-493f"
  template:
    metadata:
      labels:
        app: "rogoyalgua-493f"
    spec:
      containers:
        - name: "rogoyalgua-493f"
          image: "rogoyalacr.azurecr.io/rogoyalgua"
          ports:
          - containerPort: 80