on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: rogoyalacr.azurecr.io
        username: ${{ secrets.acr_rogoyalacr_username }}
        password: ${{ secrets.acr_rogoyalacr_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/AIG" -f  "AIG/Dockerfile" -t rogoyalacr.azurecr.io/rogoyalgua:${{ github.sha }}
        docker push rogoyalacr.azurecr.io/rogoyalgua:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_rogoyalgua_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep rogoyal-gua88fb | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace rogoyal-gua88fb`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: rogoyal-gua88fb
        container-registry-url: rogoyalacr.azurecr.io
        container-registry-username: ${{ secrets.acr_rogoyalacr_username }}
        container-registry-password: ${{ secrets.acr_rogoyalacr_password }}
        secret-name: rogoyalguadockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: rogoyal-gua88fb
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          rogoyalacr.azurecr.io/rogoyalgua:${{ github.sha }}
        imagepullsecrets: |
          rogoyalguadockerauth